# 01. 파이썬 기반의 머신러닝과 생태계의 이해


## 1.   머신러닝의 개념
---
<br>

**머신러닝**: 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

 > 머신러닝 알고리즘은 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출해 낸다.

*   지도학습 (분류/ 회귀 ...)
*   비지도학습 (클러스터링 ...)
* 강화학습
<br>

## 2.   넘파이
---
<br>

**Numerical Python**: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

기능
1. 배열 기반의 연산 가능

1-1) 빠른 배열 연산 속도

1-2) C/C++ 과 같은 저수준 언어 기반의 호환 API 제공

2. 다양한 데이터 핸들링 기능 제공



<br>

### **2-1) 넘파이 ndarray 개요**

--> 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있어 ndarray 배열의 차원까지 알 수 있음.

<br>

* np.array() : ndarray로 변환을 원하는 객제를 인자로 입력하면 ndarray를 반환

* mdarray.shape : ndarray의 차원과 크기를 튜플 형태로 나타냄

ex)

[1,2,3]인 array1의 shape는 (3,) --> 1차원 array로 3개의 데이터를 가지고 있음을 의미

array2의 shape은 (2,3) --> 2개의 row와 3개의 collumn으로 구성되어 6개의 데이터를 가지고 있음을 의미

array3의 shape은 (1,3) --> 1개의 row와 3개의 collumn으로 구성된 2차원 데이터를 의미



In [29]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태', array3.shape)

print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태 (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)
array1: 1차원, array2: 2차원, array3: 2차원


<br>

###**2-2) ndarray의 데이터 타입**

--> ndarray 내의 데이터값은 숫자 값, 문자열 값, 불 값 등이 모두 가능

--> ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능



In [30]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


--> 만일 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

ex) int형과 string형이 섞여 있는 리스트는 모두 문자열 값으로 변환

In [31]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


--> ndarray 내 데이터값의 타입 변경도 astype() 메서드를 이용해 할 수 있음

astype()에 인자로 원하는 타입을 문자열로 지정하면 됨

In [32]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


<br>

###**2-3) ndarray를 편리하게 생성하기 - arange, zeros, ones**

--> 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우, arange(), zeros(), ones()를 이용해 쉽게 ndarray를 생성할 수 있음

<br>

* arange() : array를 range()로 표현하는 것. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

* zeros() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

* ones() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환


In [33]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


<br>

###**2-4) ndarray의 차원과 크기를 변경하는 reshape()**

--> reshape()에 변환을 원하는 크기를 함수 인자로 부여하면 됨

--> reshape()는 지정된 사이즈로 변경이 불가능하면 오류 발생

In [34]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [35]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

--> -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환

ex)

array1.reshape(-1,5) --> array1과 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환하라는 의미

즉, 10개의 1차원 데이터와 호환될 수 있는 고정된 5개 칼럼에 맞는 로우 개수는 2이므로, 2X5의 2차원 ndarray로 변환

+) 물론 -1을 사용하더라도 호환될 수 없는 형태는 변환 불가

In [42]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [43]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

--> -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용

원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장


In [44]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


<br>

###**2-5) 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**

**1. 단일 값 추출**

--> ndarray 객체에 해당하는 위치의 인덱스 값을 [] 안에 입력


In [45]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]


--> 다차원 ndarray에서 단일 값 추출: 2차원의 경우 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근

--> 넘파이의 다차원 ndarray는 axis 구분을 가짐

axis 0 : 로우 방향의 축 / axis 1 : 칼럼 방향의 축

[row = 0, col = 1] --> [axis0 = 0, axis1 = 1]


In [46]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0)index 가리키는 값:', array2d[0,0])
print('(row=0, col=1)index 가리키는 값:', array2d[0,1])
print('(row=1, col=0)index 가리키는 값:', array2d[1,0])
print('(row=2, col=2)index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0)index 가리키는 값: 1
(row=0, col=1)index 가리키는 값: 2
(row=1, col=0)index 가리키는 값: 4
(row=2, col=2)index 가리키는 값: 9


**2. 슬라이싱**

--> ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출

':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1의 위치에 있는 데이터의 ndarray를 반환

In [47]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


--> 슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략이 가능

In [48]:
array1 = np.arange(start =1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


--> 2차원 ndarray에서의 슬라이싱도 1차원 ndarray에서의 슬라이싱과 유사. 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다름

--> 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환

In [49]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2]\n', array2d[0:2,0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:3, :])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


**3. 팬시 인덱싱**

--> 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식


In [50]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] ->', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] ->', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] ->', array5.tolist())

array2d[[0,1],2] -> [3, 6]
array2d[[0,1],0:2] -> [[1, 2], [4, 5]]
array2d[[0,1]] -> [[1, 2, 3], [4, 5, 6]]


**4. 불린 인덱싱**

--> 조건 필터링과 검색을 동시에 할 수 있기에 매우 자주 사용되는 인덱싱 방식

--> ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하기만 하면 됨


In [51]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값: ', array3)

array1d > 5

array1d > 5 불린 인덱싱 결과 값:  [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

In [52]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


<br>

### **2-6) 행렬의 정렬 - sort()와 argsort()**


--> np.sort() : 넘파이에서 sort()를 호출하는 방식

- 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환

--> ndarray.sort() : 행렬에서 sort()를 호출하는 방식

- 원 행렬 자체를 정렬한 형태로 변환하며 반환 값을 None

In [53]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


--> np.sort()나 ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소 정렬

내림차순으로 정렬하기 위해서는 [::-1]을 적용

In [54]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


--> 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬 수행 가능

In [55]:
array2d = np.array([[8,12],[7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


--> 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort() 이용

정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환

In [56]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

# 내림차순으로 정렬 시
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [39]:
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### **선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

**1. 행렬 내적(행렬 곱)**

--> 두 행렬 A과 B의 내적은 np.dot()을 이용해 계산 가능

In [40]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


**2. 전치 행렬**

--> 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라 함.

In [41]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
